version: 2

project_name: skuggsja

builds:
  - id: skuggsja
    main: ./cmd/skuggsja
    binary: skuggsja
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: skuggsja
    ids: [skuggsja]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: 0merUfuk
    name: skuggsja
  prerelease: auto

checksum:
  name_template: checksums.txt

changelog:
  use: git
